// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.snoopconsulting.antecedentes.domain;

import com.snoopconsulting.antecedentes.domain.ContactoDataOnDemand;
import com.snoopconsulting.antecedentes.domain.ContactoIntegrationTest;
import com.snoopconsulting.antecedentes.repository.jpa.ContactoRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContactoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContactoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContactoIntegrationTest: @Transactional;
    
    @Autowired
    ContactoDataOnDemand ContactoIntegrationTest.dod;
    
    @Autowired
    ContactoRepository ContactoIntegrationTest.contactoRepository;
    
    @Test
    public void ContactoIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Contacto' failed to initialize correctly", dod.getRandomContacto());
        long count = contactoRepository.count();
        Assert.assertTrue("Counter for 'Contacto' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContactoIntegrationTest.testFind() {
        Contacto obj = dod.getRandomContacto();
        Assert.assertNotNull("Data on demand for 'Contacto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contacto' failed to provide an identifier", id);
        obj = contactoRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Contacto' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Contacto' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ContactoIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Contacto' failed to initialize correctly", dod.getRandomContacto());
        long count = contactoRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Contacto', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Contacto> result = contactoRepository.findAll();
        Assert.assertNotNull("Find all method for 'Contacto' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Contacto' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContactoIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Contacto' failed to initialize correctly", dod.getRandomContacto());
        long count = contactoRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Contacto> result = contactoRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Contacto' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Contacto' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContactoIntegrationTest.testFlush() {
        Contacto obj = dod.getRandomContacto();
        Assert.assertNotNull("Data on demand for 'Contacto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contacto' failed to provide an identifier", id);
        obj = contactoRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Contacto' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContacto(obj);
        Integer currentVersion = obj.getVersion();
        contactoRepository.flush();
        Assert.assertTrue("Version for 'Contacto' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactoIntegrationTest.testSaveUpdate() {
        Contacto obj = dod.getRandomContacto();
        Assert.assertNotNull("Data on demand for 'Contacto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contacto' failed to provide an identifier", id);
        obj = contactoRepository.findOne(id);
        boolean modified =  dod.modifyContacto(obj);
        Integer currentVersion = obj.getVersion();
        Contacto merged = contactoRepository.save(obj);
        contactoRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Contacto' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactoIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Contacto' failed to initialize correctly", dod.getRandomContacto());
        Contacto obj = dod.getNewTransientContacto(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Contacto' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Contacto' identifier to be null", obj.getId());
        try {
            contactoRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        contactoRepository.flush();
        Assert.assertNotNull("Expected 'Contacto' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ContactoIntegrationTest.testDelete() {
        Contacto obj = dod.getRandomContacto();
        Assert.assertNotNull("Data on demand for 'Contacto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contacto' failed to provide an identifier", id);
        obj = contactoRepository.findOne(id);
        contactoRepository.delete(obj);
        contactoRepository.flush();
        Assert.assertNull("Failed to remove 'Contacto' with identifier '" + id + "'", contactoRepository.findOne(id));
    }
    
}
