// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.snoopconsulting.antecedentes.domain;

import com.snoopconsulting.antecedentes.domain.CuentaDataOnDemand;
import com.snoopconsulting.antecedentes.domain.CuentaIntegrationTest;
import com.snoopconsulting.antecedentes.repository.jpa.CuentaRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CuentaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CuentaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CuentaIntegrationTest: @Transactional;
    
    @Autowired
    CuentaDataOnDemand CuentaIntegrationTest.dod;
    
    @Autowired
    CuentaRepository CuentaIntegrationTest.cuentaRepository;
    
    @Test
    public void CuentaIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", dod.getRandomCuenta());
        long count = cuentaRepository.count();
        Assert.assertTrue("Counter for 'Cuenta' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CuentaIntegrationTest.testFind() {
        Cuenta obj = dod.getRandomCuenta();
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to provide an identifier", id);
        obj = cuentaRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Cuenta' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Cuenta' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CuentaIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", dod.getRandomCuenta());
        long count = cuentaRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Cuenta', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Cuenta> result = cuentaRepository.findAll();
        Assert.assertNotNull("Find all method for 'Cuenta' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Cuenta' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CuentaIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", dod.getRandomCuenta());
        long count = cuentaRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Cuenta> result = cuentaRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Cuenta' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Cuenta' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CuentaIntegrationTest.testFlush() {
        Cuenta obj = dod.getRandomCuenta();
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to provide an identifier", id);
        obj = cuentaRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Cuenta' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCuenta(obj);
        Integer currentVersion = obj.getVersion();
        cuentaRepository.flush();
        Assert.assertTrue("Version for 'Cuenta' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CuentaIntegrationTest.testSaveUpdate() {
        Cuenta obj = dod.getRandomCuenta();
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to provide an identifier", id);
        obj = cuentaRepository.findOne(id);
        boolean modified =  dod.modifyCuenta(obj);
        Integer currentVersion = obj.getVersion();
        Cuenta merged = cuentaRepository.save(obj);
        cuentaRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Cuenta' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CuentaIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", dod.getRandomCuenta());
        Cuenta obj = dod.getNewTransientCuenta(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Cuenta' identifier to be null", obj.getId());
        try {
            cuentaRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        cuentaRepository.flush();
        Assert.assertNotNull("Expected 'Cuenta' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CuentaIntegrationTest.testDelete() {
        Cuenta obj = dod.getRandomCuenta();
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cuenta' failed to provide an identifier", id);
        obj = cuentaRepository.findOne(id);
        cuentaRepository.delete(obj);
        cuentaRepository.flush();
        Assert.assertNull("Failed to remove 'Cuenta' with identifier '" + id + "'", cuentaRepository.findOne(id));
    }
    
}
