// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.snoopconsulting.antecedentes.domain;

import com.snoopconsulting.antecedentes.domain.Cuenta;
import com.snoopconsulting.antecedentes.domain.CuentaDataOnDemand;
import com.snoopconsulting.antecedentes.repository.jpa.CuentaRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CuentaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CuentaDataOnDemand: @Component;
    
    private Random CuentaDataOnDemand.rnd = new SecureRandom();
    
    private List<Cuenta> CuentaDataOnDemand.data;
    
    @Autowired
    CuentaRepository CuentaDataOnDemand.cuentaRepository;
    
    public Cuenta CuentaDataOnDemand.getNewTransientCuenta(int index) {
        Cuenta obj = new Cuenta();
        setDireccion(obj, index);
        setIdCrm(obj, index);
        setLinkCRM(obj, index);
        setNombre(obj, index);
        setTelefono(obj, index);
        setVertical(obj, index);
        return obj;
    }
    
    public void CuentaDataOnDemand.setDireccion(Cuenta obj, int index) {
        String direccion = "direccion_" + index;
        obj.setDireccion(direccion);
    }
    
    public void CuentaDataOnDemand.setIdCrm(Cuenta obj, int index) {
        String idCrm = "idCrm_" + index;
        obj.setIdCrm(idCrm);
    }
    
    public void CuentaDataOnDemand.setLinkCRM(Cuenta obj, int index) {
        String linkCRM = "linkCRM_" + index;
        obj.setLinkCRM(linkCRM);
    }
    
    public void CuentaDataOnDemand.setNombre(Cuenta obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void CuentaDataOnDemand.setTelefono(Cuenta obj, int index) {
        String telefono = "telefono_" + index;
        obj.setTelefono(telefono);
    }
    
    public void CuentaDataOnDemand.setVertical(Cuenta obj, int index) {
        String vertical = "vertical_" + index;
        obj.setVertical(vertical);
    }
    
    public Cuenta CuentaDataOnDemand.getSpecificCuenta(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Cuenta obj = data.get(index);
        Long id = obj.getId();
        return cuentaRepository.findOne(id);
    }
    
    public Cuenta CuentaDataOnDemand.getRandomCuenta() {
        init();
        Cuenta obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return cuentaRepository.findOne(id);
    }
    
    public boolean CuentaDataOnDemand.modifyCuenta(Cuenta obj) {
        return false;
    }
    
    public void CuentaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = cuentaRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Cuenta' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Cuenta>();
        for (int i = 0; i < 10; i++) {
            Cuenta obj = getNewTransientCuenta(i);
            try {
                cuentaRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            cuentaRepository.flush();
            data.add(obj);
        }
    }
    
}
