// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.snoopconsulting.antecedentes.domain;

import com.snoopconsulting.antecedentes.domain.Pais;
import com.snoopconsulting.antecedentes.domain.PaisDataOnDemand;
import com.snoopconsulting.antecedentes.repository.jpa.PaisRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PaisDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PaisDataOnDemand: @Component;
    
    private Random PaisDataOnDemand.rnd = new SecureRandom();
    
    private List<Pais> PaisDataOnDemand.data;
    
    @Autowired
    PaisRepository PaisDataOnDemand.paisRepository;
    
    public Pais PaisDataOnDemand.getNewTransientPais(int index) {
        Pais obj = new Pais();
        setNombre(obj, index);
        return obj;
    }
    
    public void PaisDataOnDemand.setNombre(Pais obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public Pais PaisDataOnDemand.getSpecificPais(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Pais obj = data.get(index);
        Long id = obj.getId();
        return paisRepository.findOne(id);
    }
    
    public Pais PaisDataOnDemand.getRandomPais() {
        init();
        Pais obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return paisRepository.findOne(id);
    }
    
    public boolean PaisDataOnDemand.modifyPais(Pais obj) {
        return false;
    }
    
    public void PaisDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = paisRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Pais' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Pais>();
        for (int i = 0; i < 10; i++) {
            Pais obj = getNewTransientPais(i);
            try {
                paisRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            paisRepository.flush();
            data.add(obj);
        }
    }
    
}
