// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.snoopconsulting.antecedentes.domain;

import com.snoopconsulting.antecedentes.domain.PaisDataOnDemand;
import com.snoopconsulting.antecedentes.domain.PaisIntegrationTest;
import com.snoopconsulting.antecedentes.repository.jpa.PaisRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PaisIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PaisIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PaisIntegrationTest: @Transactional;
    
    @Autowired
    PaisDataOnDemand PaisIntegrationTest.dod;
    
    @Autowired
    PaisRepository PaisIntegrationTest.paisRepository;
    
    @Test
    public void PaisIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", dod.getRandomPais());
        long count = paisRepository.count();
        Assert.assertTrue("Counter for 'Pais' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PaisIntegrationTest.testFind() {
        Pais obj = dod.getRandomPais();
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pais' failed to provide an identifier", id);
        obj = paisRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Pais' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Pais' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PaisIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", dod.getRandomPais());
        long count = paisRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Pais', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Pais> result = paisRepository.findAll();
        Assert.assertNotNull("Find all method for 'Pais' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Pais' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PaisIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", dod.getRandomPais());
        long count = paisRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Pais> result = paisRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Pais' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Pais' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PaisIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", dod.getRandomPais());
        Pais obj = dod.getNewTransientPais(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Pais' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Pais' identifier to be null", obj.getId());
        try {
            paisRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        paisRepository.flush();
        Assert.assertNotNull("Expected 'Pais' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PaisIntegrationTest.testDelete() {
        Pais obj = dod.getRandomPais();
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pais' failed to provide an identifier", id);
        obj = paisRepository.findOne(id);
        paisRepository.delete(obj);
        paisRepository.flush();
        Assert.assertNull("Failed to remove 'Pais' with identifier '" + id + "'", paisRepository.findOne(id));
    }
    
}
