// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.snoopconsulting.antecedentes.domain;

import com.snoopconsulting.antecedentes.domain.SBUDataOnDemand;
import com.snoopconsulting.antecedentes.domain.SBUIntegrationTest;
import com.snoopconsulting.antecedentes.repository.jpa.SBURepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SBUIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SBUIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SBUIntegrationTest: @Transactional;
    
    @Autowired
    SBUDataOnDemand SBUIntegrationTest.dod;
    
    @Autowired
    SBURepository SBUIntegrationTest.sBURepository;
    
    @Test
    public void SBUIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'SBU' failed to initialize correctly", dod.getRandomSBU());
        long count = sBURepository.count();
        Assert.assertTrue("Counter for 'SBU' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SBUIntegrationTest.testFind() {
        SBU obj = dod.getRandomSBU();
        Assert.assertNotNull("Data on demand for 'SBU' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SBU' failed to provide an identifier", id);
        obj = sBURepository.findOne(id);
        Assert.assertNotNull("Find method for 'SBU' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SBU' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SBUIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'SBU' failed to initialize correctly", dod.getRandomSBU());
        long count = sBURepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'SBU', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SBU> result = sBURepository.findAll();
        Assert.assertNotNull("Find all method for 'SBU' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SBU' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SBUIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'SBU' failed to initialize correctly", dod.getRandomSBU());
        long count = sBURepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SBU> result = sBURepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'SBU' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SBU' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SBUIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'SBU' failed to initialize correctly", dod.getRandomSBU());
        SBU obj = dod.getNewTransientSBU(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SBU' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SBU' identifier to be null", obj.getId());
        try {
            sBURepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        sBURepository.flush();
        Assert.assertNotNull("Expected 'SBU' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SBUIntegrationTest.testDelete() {
        SBU obj = dod.getRandomSBU();
        Assert.assertNotNull("Data on demand for 'SBU' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SBU' failed to provide an identifier", id);
        obj = sBURepository.findOne(id);
        sBURepository.delete(obj);
        sBURepository.flush();
        Assert.assertNull("Failed to remove 'SBU' with identifier '" + id + "'", sBURepository.findOne(id));
    }
    
}
