// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.snoopconsulting.antecedentes.domain;

import com.snoopconsulting.antecedentes.domain.ValidacionDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ValidacionDataOnDemand_Roo_Configurable {
    
    declare @type: ValidacionDataOnDemand: @Configurable;
    
}
