// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.snoopconsulting.antecedentes.domain;

import com.snoopconsulting.antecedentes.domain.ValidacionDataOnDemand;
import com.snoopconsulting.antecedentes.domain.ValidacionIntegrationTest;
import com.snoopconsulting.antecedentes.repository.jpa.ValidacionRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ValidacionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ValidacionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ValidacionIntegrationTest: @Transactional;
    
    @Autowired
    ValidacionDataOnDemand ValidacionIntegrationTest.dod;
    
    @Autowired
    ValidacionRepository ValidacionIntegrationTest.validacionRepository;
    
    @Test
    public void ValidacionIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Validacion' failed to initialize correctly", dod.getRandomValidacion());
        long count = validacionRepository.count();
        Assert.assertTrue("Counter for 'Validacion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ValidacionIntegrationTest.testFind() {
        Validacion obj = dod.getRandomValidacion();
        Assert.assertNotNull("Data on demand for 'Validacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Validacion' failed to provide an identifier", id);
        obj = validacionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Validacion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Validacion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ValidacionIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Validacion' failed to initialize correctly", dod.getRandomValidacion());
        long count = validacionRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Validacion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Validacion> result = validacionRepository.findAll();
        Assert.assertNotNull("Find all method for 'Validacion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Validacion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ValidacionIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Validacion' failed to initialize correctly", dod.getRandomValidacion());
        long count = validacionRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Validacion> result = validacionRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Validacion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Validacion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ValidacionIntegrationTest.testFlush() {
        Validacion obj = dod.getRandomValidacion();
        Assert.assertNotNull("Data on demand for 'Validacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Validacion' failed to provide an identifier", id);
        obj = validacionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Validacion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyValidacion(obj);
        Integer currentVersion = obj.getVersion();
        validacionRepository.flush();
        Assert.assertTrue("Version for 'Validacion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ValidacionIntegrationTest.testSaveUpdate() {
        Validacion obj = dod.getRandomValidacion();
        Assert.assertNotNull("Data on demand for 'Validacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Validacion' failed to provide an identifier", id);
        obj = validacionRepository.findOne(id);
        boolean modified =  dod.modifyValidacion(obj);
        Integer currentVersion = obj.getVersion();
        Validacion merged = validacionRepository.save(obj);
        validacionRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Validacion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ValidacionIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Validacion' failed to initialize correctly", dod.getRandomValidacion());
        Validacion obj = dod.getNewTransientValidacion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Validacion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Validacion' identifier to be null", obj.getId());
        try {
            validacionRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        validacionRepository.flush();
        Assert.assertNotNull("Expected 'Validacion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ValidacionIntegrationTest.testDelete() {
        Validacion obj = dod.getRandomValidacion();
        Assert.assertNotNull("Data on demand for 'Validacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Validacion' failed to provide an identifier", id);
        obj = validacionRepository.findOne(id);
        validacionRepository.delete(obj);
        validacionRepository.flush();
        Assert.assertNull("Failed to remove 'Validacion' with identifier '" + id + "'", validacionRepository.findOne(id));
    }
    
}
