/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-02-05 00:13:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class casa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style1.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/validateForm.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jqueryAPI.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/JavaScriptAPI.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/casa.js\"></script>\r\n");
      out.write("<title>Â¡Bienvenido a RESTafar I!</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<p id=\"title\">RESTafar I!</p>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<a class=\"ship\" href=\"index.jsp\">Home</a>\r\n");
      out.write("\t\t\t<a class=\"ship\" href=\"#\">Como</a>\r\n");
      out.write("\t\t\t<a class=\"ship\" href=\"#\">Contacto</a>\r\n");
      out.write("\t\t</nav>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"body\">\r\n");
      out.write("\t\t<div id=\"container-left\">\r\n");
      out.write("\t\t\t<div class=\"stage\">\r\n");
      out.write("\t\t\t\t<label class=\"work\">Mascotas:</label>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t");
      java.util.Date date = null;
      date = (java.util.Date) _jspx_page_context.getAttribute("date", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (date == null){
        date = new java.util.Date();
        _jspx_page_context.setAttribute("date", date, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write(" \r\n");
      out.write("<p>The date/time is ");
      out.print( date );
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><input type=\"checkbox\" /><i class=\"doneby\"></i></li>\r\n");
      out.write("\t\t\t\t\t<li>Sasha:<input type=\"checkbox\" onClick=\"chkboxClick()\"/><i class=\"doneby\">(realizado por)</i></li>\r\n");
      out.write("\t\t\t\t\t<li>Mirko:<input type=\"checkbox\" /><i class=\"doneby\">(realizado por)</i></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"container-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"container-right\">Monkey D. Luffy - Ivuch D. Kong</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\">FOOTER</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
