/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-02-03 23:25:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class formRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/validateForm.css\" />\r\n");
      out.write("<title>¡Bienvenido a RESTafar I!</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<p id=\"title\">RESTafar I!</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"body\">\r\n");
      out.write("\t\t<div id=\"container-left\">\r\n");
      out.write("\t\t\t<div class=\"linkToResource\"><a href=\"index.jsp\">HOME</a></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"container-center\">\r\n");
      out.write("\t\t\t<form action=\"rest/user\" method=\"POST\">\r\n");
      out.write("\t\t\t<label>Nombres:</label> <input type=\"text\" name=\"name\"><br/>\r\n");
      out.write("\t\t\t<label>Apellido: </label> <input type=\"text\" name=\"lname\"><br/>\r\n");
      out.write("\t\t\t<label>Contraseña: </label> <input type=\"password\" name=\"pass\"><br/>\r\n");
      out.write("\t\t\t<label>Confirmar Contraseña: </label> <input type=\"password\" name=\"confirmPass\"><br/>\r\n");
      out.write("\t\t\t<label>E-mail: </label> <input type=\"email\" name=\"email\"><br/>\r\n");
      out.write("\t\t\t<input type=\"submit\" id=\"formButton\" value=\"Submit\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"container-right\">Monkey D. Luffy - Ivuch D. Kong</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\">FOOTER</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
