/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-03-28 02:18:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction clear5(){\r\n");
      out.write("\t\tdocument.getElementById('restResponses').value = '';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getHello(path){\r\n");
      out.write("\t\tif(window.XMLHttpRequest) {\r\n");
      out.write("\t\t    peticion_http = new XMLHttpRequest();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(window.ActiveXObject) {\r\n");
      out.write("\t\t\tpeticion_http = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tpeticion_http.onreadystatechange = muestraContenido;\r\n");
      out.write(" \r\n");
      out.write("\t\t// Realizar peticion HTTP\r\n");
      out.write("\t\tpeticion_http.open('GET', path, true);\r\n");
      out.write("\t\tpeticion_http.send(null);\r\n");
      out.write("\t}\r\n");
      out.write("\t\tfunction muestraContenido() {\r\n");
      out.write("\t      if(peticion_http.readyState == 4) {\r\n");
      out.write("\t      \tif(peticion_http.status == 200) {\r\n");
      out.write("\t      \t\tdocument.getElementById('restResponses').value = peticion_http.responseText;\r\n");
      out.write("\t      \t}\r\n");
      out.write("    \t  }\r\n");
      out.write("  \t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<title>¡Bienvenido a RESTafar I!</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\"><p id=\"title\">Jah RESTafar I!</p></div>\r\n");
      out.write("\t<div id=\"body\">\r\n");
      out.write("\t\t<div id=\"container-left\">\r\n");
      out.write("\t\t\t<input id=\"searchEngineBox\" type=\"search\" placeholder=\"Search API REST...\"/>\r\n");
      out.write("\t\t\t<div class=\"linkToResource\"><a href=\"#\" onClick=\"getHello('http://localhost:8082/WebI/rest/hello/REST%20response%20Ok');\">LINK 1</a></div>\r\n");
      out.write("\t\t\t<div class=\"linkToResource\"><a href=\"#\" onClick=\"getHello('http://localhost:8082/WebI/rest/hello/REST%20OP!');\">LINK 1</a></div>\r\n");
      out.write("\t\t\t<div class=\"linkToResource\"><a href=\"#\" onClick=\"getHello('http://localhost:8082/WebI/rest/hello/Ok?');\">LINK 1</a></div>\r\n");
      out.write("\t\t\t<div class=\"linkToResource\"><a href=\"#\" onClick=\"getHello('https://api.mercadolibre.com/users/1234');\">MeLi user1234</a></div>\r\n");
      out.write("\t\t\t<div class=\"linkToResource\"><a href=\"#\" onClick=\"getHello('http://localhost:8082/WebI/rest/hello/REST%20response%20Ok');\">LINK 1</a></div>\r\n");
      out.write("\t\t\t<div class=\"linkToResource\"><a href=\"#\" onClick=\"getHello('http://localhost:8082/WebI/rest/hello/REST%20response%20Ok');\">LINK 1</a></div>\r\n");
      out.write("\t\t\t<div class=\"linkToResource\"><a href=\"login.jsp\" onClick=\"\">Log-in To/TheWeb!</a></div>\r\n");
      out.write("\t\t\t<div class=\"linkToResource\"><a href=\"casa/inicio.jsp\">Casa App!</a></div>\r\n");
      out.write("\t\t\t<div class=\"linkToResource\"><a href=\"functions/actualizetextlimit.jsp\"><i>functios</i> App</a></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"container-center\">\r\n");
      out.write("<!-- \t\t\t<p>Rastafar I es un movimiento, no una ideología, Rasta es el momento y no una idea estancada en el tiempo, esa es la diferencia. Jah es como lo llamamos, y por varias razones... Jah es el dios inicial del ser Humano desde tiempos inmemoriables, antes conocido como RA, el Dios del Sol, luego como Jahovia o Jehová, por el pueblo Judío, más tarde reencarnado en Jahsua, Yashua o Jesús (su nombre en lengua latina) para el cristianismo y luego como JAH o YHVH para el Rastafarismo. Por eso JAH, YA es el momento.</p>  -->\r\n");
      out.write("\t\t\t<textarea id=\"restResponses\"></textarea>\r\n");
      out.write("\t\t\t<input  type=\"button\" onClick=\"clear5();\" value=\"Clear box\" id=\"clearButton\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<iframe width=\"254\" height=\"510\" src=\"https://www.youtube.com/embed/G3jtfsJdy8s\" frameborder=\"0\" allowfullscreen></iframe>\r\n");
      out.write("\t\t<object codetype=\"application/java\" classid=\"java:Main.class\"\r\n");
      out.write("   archive=\"C:\\Users\\MaximilianoIván\\workspace\\Ajedrez\\target\\Ajedrez-0.0.1-SNAPSHOT.jar\" width=\"740\" height=\"400\"></object>\r\n");
      out.write("\t\t<applet code=\"Main.class\" archive=\"C:\\Users\\MaximilianoIván\\workspace\\Ajedrez\\target\\Ajedrez-0.0.1-SNAPSHOT.jar\"\r\n");
      out.write("   width=\"740\" height=\"400\"></applet>\r\n");
      out.write("\t\t<div id=\"container-right\">Monkey D. Luffy - Ivuch D. Kong</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\">FOOTER</div>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
